/**
 * Доставка пароля и passphrase системному ssh
 *
 * Клиент OpenSSH не читает пароль со stdin — он запрашивает его через
 * программу, указанную в SSH_ASKPASS. Это штатный механизм, поэтому
 * никаких сторонних обёрток вроде sshpass не требуется.
 *
 * Секрет живёт только в окружении конкретного запускаемого процесса:
 *  - в аргументы он не попадает никогда (argv виден всей системе через ps);
 *  - на диск не пишется (скрипт содержит только чтение переменной);
 *  - окружение процесса читает лишь его владелец и root — тот же круг лиц,
 *    что уже имеет доступ к файлу профилей с паролем внутри.
 */

import { chmodSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import type { RunnerConfig } from './ssh-args.js';

/** Имя переменной, через которую секрет попадает в askpass-скрипт */
export const SECRET_ENV_VAR = 'SSH_MCP_SECRET';

/** Имя askpass-скрипта внутри управляющего каталога */
export const ASKPASS_SCRIPT_NAME = 'askpass.sh';

/**
 * Содержимое скрипта: печатает секрет, полученный из окружения.
 * Сам секрет в файле не хранится.
 */
const ASKPASS_SCRIPT = `#!/bin/sh
# Generated by ssh-mcp-server. Prints the secret passed via the environment.
# The secret is never stored in this file.
printf '%s' "$${SECRET_ENV_VAR}"
`;

/**
 * Создать (или обновить) askpass-скрипт и вернуть путь к нему
 */
export function ensureAskpassScript(controlDir: string): string {
  // Каталог мог быть не создан: при выключенном мультиплексировании
  // управляющие сокеты не нужны, а askpass — нужен
  mkdirSync(controlDir, { recursive: true, mode: 0o700 });
  const scriptPath = join(controlDir, ASKPASS_SCRIPT_NAME);
  writeFileSync(scriptPath, ASKPASS_SCRIPT, { mode: 0o700 });
  // writeFileSync применяет mode только при создании файла — существующему
  // файлу права надо выставить явно
  chmodSync(scriptPath, 0o700);
  return scriptPath;
}

/**
 * Какой секрет нужен профилю.
 *
 * Если задан ключ, ssh спросит passphrase к нему; пароль пользователя
 * понадобится только когда ключа нет.
 */
export function selectSecret(config: RunnerConfig): string | undefined {
  if (config.privateKeyPath && config.passphrase) {
    return config.passphrase;
  }
  if (!config.privateKeyPath && config.password) {
    return config.password;
  }
  return config.passphrase ?? config.password;
}

/**
 * Окружение для запуска ssh.
 *
 * Возвращает новый объект — базовое окружение процесса не изменяется,
 * поэтому секрет не утечёт в другие запускаемые команды.
 */
export function buildRunnerEnv(input: {
  config: RunnerConfig;
  askpassScriptPath?: string;
  baseEnv?: NodeJS.ProcessEnv;
}): NodeJS.ProcessEnv {
  const { config, askpassScriptPath, baseEnv = process.env } = input;
  const env: NodeJS.ProcessEnv = { ...baseEnv };

  // Чужое значение не должно случайно попасть в дочерний процесс
  delete env[SECRET_ENV_VAR];

  const secret = selectSecret(config);
  if (!secret || !askpassScriptPath) {
    return env;
  }

  env.SSH_ASKPASS = askpassScriptPath;
  // Без force клиент спрашивает секрет в терминале, а терминала у нас нет
  env.SSH_ASKPASS_REQUIRE = 'force';
  env[SECRET_ENV_VAR] = secret;

  // Страховка для сборок, которые всё ещё смотрят на наличие DISPLAY
  if (!env.DISPLAY) {
    env.DISPLAY = ':0';
  }

  return env;
}

/**
 * Замаскировать секрет в тексте перед выводом или логированием.
 *
 * Нужно там, где вывод команды может содержать эхо введённого секрета.
 */
export function redactSecret(text: string, secret?: string): string {
  if (!secret || secret.length === 0) return text;
  return text.split(secret).join('***');
}
