/**
 * Delivering the password and passphrase to the system ssh
 *
 * The OpenSSH client doesn't read a password from stdin — it requests it
 * through the program named in SSH_ASKPASS. This is a built-in mechanism,
 * so no third-party wrappers like sshpass are needed.
 *
 * The secret lives only in the environment of the specific process being
 * spawned:
 *  - it never ends up in arguments (argv is visible system-wide via ps);
 *  - it isn't written to disk (the script only reads the variable);
 *  - process environment is readable only by its owner and root — the same
 *    circle that already has access to the profile file with the password inside.
 */

import { chmodSync, mkdirSync, renameSync, writeFileSync } from 'fs';
import { join } from 'path';
import type { RunnerConfig } from './ssh-args.js';

/** Name of the variable that carries the secret into the askpass script */
export const SECRET_ENV_VAR = 'SSH_MCP_SECRET';

/** Name of the askpass script inside the control directory */
export const ASKPASS_SCRIPT_NAME = 'askpass.sh';

/**
 * Script contents: prints the secret taken from the environment.
 * The secret itself is not stored in the file.
 */
const ASKPASS_SCRIPT = `#!/bin/sh
# Generated by ssh-mcp-server. Prints the secret passed via the environment.
# The secret is never stored in this file.
printf '%s' "$${SECRET_ENV_VAR}"
`;

/**
 * Create (or refresh) the askpass script and return its path.
 *
 * The script is written alongside the target and put in place by renaming:
 * the control directory is shared across all profiles and all server
 * processes, so a sibling ssh may be executing the same file at write time.
 * Writing straight to the final path would truncate it first — the client
 * would receive an empty secret and be denied login.
 */
export function ensureAskpassScript(controlDir: string): string {
  // The directory may not have been created: with multiplexing disabled,
  // control sockets aren't needed, but askpass still is
  mkdirSync(controlDir, { recursive: true, mode: 0o700 });
  const scriptPath = join(controlDir, ASKPASS_SCRIPT_NAME);
  // Named by process id: within one process the write is synchronous, while
  // a sibling server process writes into the same shared directory
  const tempPath = `${scriptPath}.${process.pid}`;
  writeFileSync(tempPath, ASKPASS_SCRIPT, { mode: 0o700 });
  // writeFileSync only applies mode on file creation — a temp file surviving
  // from a previous run needs its permissions set explicitly
  chmodSync(tempPath, 0o700);
  renameSync(tempPath, scriptPath);
  return scriptPath;
}

/**
 * Which secret the profile needs.
 *
 * With a key configured, ssh will ask for its passphrase; the user's
 * password is only needed when there is no key.
 */
export function selectSecret(config: RunnerConfig): string | undefined {
  if (config.privateKeyPath && config.passphrase) {
    return config.passphrase;
  }
  if (!config.privateKeyPath && config.password) {
    return config.password;
  }
  return config.passphrase ?? config.password;
}

/**
 * Environment for running ssh.
 *
 * Returns a new object — the base process environment is left untouched,
 * so the secret can't leak into other spawned commands.
 */
export function buildRunnerEnv(input: {
  config: RunnerConfig;
  askpassScriptPath?: string;
  baseEnv?: NodeJS.ProcessEnv;
}): NodeJS.ProcessEnv {
  const { config, askpassScriptPath, baseEnv = process.env } = input;
  const env: NodeJS.ProcessEnv = { ...baseEnv };

  // A leftover value from elsewhere must not slip into the child process
  delete env[SECRET_ENV_VAR];

  const secret = selectSecret(config);
  if (!secret || !askpassScriptPath) {
    return env;
  }

  env.SSH_ASKPASS = askpassScriptPath;
  // Without force the client asks for the secret in the terminal, and there is no terminal here
  env.SSH_ASKPASS_REQUIRE = 'force';
  env[SECRET_ENV_VAR] = secret;

  // A safety net for builds that still check for a DISPLAY value
  if (!env.DISPLAY) {
    env.DISPLAY = ':0';
  }

  return env;
}
